feat: implemented deatil posting screen, feat: image from establishme…
Viperise/ReachOut-Web pull request #20
Opened 2024-08-24 15:19 UTC by YorranCarvalho

2024-08-24 19:47 UTC, isabela-lima requested changes

2024-08-24 19:47 UTC, isabela-lima commented on src/app/(pages)/postings/[posting]/components/editButtom.tsx
Você poderia usar os botões do next-ui? eles já tem uma prop para adicionar icons no inicio ou final

2024-08-24 19:47 UTC, isabela-lima commented on src/app/(pages)/postings/[posting]/components/editButtom.tsx
Você pode inclusive apagar esse código e usar diretamente na pagina

2024-08-24 19:47 UTC, isabela-lima commented on src/app/(pages)/postings/[posting]/components/imagePosting.tsx
Da mesma forma aqui você pode utilizar o componente de imagem do next-ui diretamente no codigo da pagina

2024-08-24 19:47 UTC, isabela-lima commented on src/app/(pages)/postings/[posting]/page.tsx
Como expliquei nos outros comentarios de preferencia use os recursos do proprio tailwind e next ui para montar a pagina

2024-08-24 19:47 UTC, isabela-lima commented on src/base/mock/index.ts
> +    imgOwner:
logo logo vamos parar de usar esses mocks mas por enquanto use esse link para qualquer imagem utilizada: https://picsum.photos/200/300

_esses links do discord estão pesando bastante o app ao carregar_

2024-08-26 22:46 UTC, YorranCarvalho commented on src/app/(pages)/postings/[posting]/components/editButtom.tsx
resolvido

2024-08-26 23:03 UTC, YorranCarvalho commented on src/base/mock/index.ts
> +    imgOwner:
feito

2024-08-26 23:04 UTC, YorranCarvalho commented on src/app/(pages)/postings/[posting]/page.tsx
tudo alterado (os que consegui lembrar de trocar)

2024-08-26 23:04 UTC, YorranCarvalho commented on src/app/(pages)/postings/[posting]/components/imagePosting.tsx
alterado tbm

2024-08-26 23:34 UTC, isabela-lima approved these changes

2024-08-26 23:35 UTC, merged